//! Live sweep over every documented `GET` collection endpoint without
//! path parameters.
//!
//! This file is generated by `scripts/generate_endpoint_manifest.py`.

use rentman_client::endpoint::ExecutableEndpoint;
use rentman_client::{RentmanClient, endpoint};
use serde::{Serialize, de::DeserializeOwned};

async fn check<E>(client: &RentmanClient, failures: &mut Vec<(&'static str, String)>)
where
    E: ExecutableEndpoint,
    E::Request: Serialize,
    E::Response: DeserializeOwned,
{
    if let Err(error) = client.endpoint::<E>().query_param("limit", 1).send().await {
        failures.push((E::SPEC.operation_id, format!("{error:#}")));
    }
}

/// Calls every documented `GET` collection endpoint without path parameters
/// with `limit=1` and returns the operations whose live calls failed.
pub async fn sweep_collections(client: &RentmanClient) -> Vec<(&'static str, String)> {
    let mut failures = Vec::new();
    check::<endpoint::GetAccessoryCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetActualContentCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetAlternativeCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetAppointmentCrewCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetAppointmentCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetContactPersonCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetContactCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetContractCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetProjectCostCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetCrewCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetCrewAvailabilityCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetCrewRatesCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetEquipmentCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetEquipmentAssignedSerialsCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetEquipmentSetContentCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetExtraInputFieldCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetFactorGroupsCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetFactorsCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetFileFolderCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetFileCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetFolderCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetInvitationsCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetInvoiceLineCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetFactuurCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetLeaveMutationsCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetLeaveRequestCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetLeaveTypesCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetLedgerCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetPaymentCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetProjectCrewCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetProjectEquipmentCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetProjectEquipmentGroupCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetProjectFunctionGroupCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetProjectFunctionCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetProjectRequestEquipmentCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetProjectRequestCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetProjectCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetProjectTypeCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetProjectVehicleCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetPurchaseOrderCostCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetPurchaseOrderGlobalCostCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetPurchaseOrderCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetQuotationCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetCrewRateFactorCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetCrewRateCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetRepairCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetSerialNumberCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetStatusCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetStockLocationCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetStockMovementCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetSubprojectCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetSubrentalEquipmentCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetSubrentalEquipmentGroupCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetSubrentalCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetSubtaskCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetSupplierCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetTaskAssignmentCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetTaskCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetTaskStatusCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetTaxClassCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetTimeRegistrationCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetTimeRegistrationActivityCollectionEndpoint>(client, &mut failures).await;
    check::<endpoint::GetVehicleCollectionEndpoint>(client, &mut failures).await;
    failures
}
