//! One live test per documented `GET` collection endpoint without path
//! parameters: each calls the endpoint with `limit=1` and decodes the
//! response through the typed models.
//!
//! This file is generated by `scripts/generate_endpoint_manifest.py`.

use super::live_client;
use rentman_client::endpoint::{self, ExecutableEndpoint};
use serde::{Serialize, de::DeserializeOwned};

async fn check<E>()
where
    E: ExecutableEndpoint,
    E::Request: Serialize,
    E::Response: DeserializeOwned,
{
    if let Err(error) = live_client()
        .endpoint::<E>()
        .query_param("limit", 1)
        .send()
        .await
    {
        panic!(
            "{} failed against the live API: {error:#}",
            E::SPEC.operation_id
        );
    }
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_accessory_collection() {
    check::<endpoint::GetAccessoryCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_actual_content_collection() {
    check::<endpoint::GetActualContentCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_alternative_collection() {
    check::<endpoint::GetAlternativeCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_appointment_crew_collection() {
    check::<endpoint::GetAppointmentCrewCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_appointment_collection() {
    check::<endpoint::GetAppointmentCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_contact_person_collection() {
    check::<endpoint::GetContactPersonCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_contact_collection() {
    check::<endpoint::GetContactCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_contract_collection() {
    check::<endpoint::GetContractCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_project_cost_collection() {
    check::<endpoint::GetProjectCostCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_crew_collection() {
    check::<endpoint::GetCrewCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_crew_availability_collection() {
    check::<endpoint::GetCrewAvailabilityCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_crew_rates_collection() {
    check::<endpoint::GetCrewRatesCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_equipment_collection() {
    check::<endpoint::GetEquipmentCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_equipment_assigned_serials_collection() {
    check::<endpoint::GetEquipmentAssignedSerialsCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_equipment_set_content_collection() {
    check::<endpoint::GetEquipmentSetContentCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_extra_input_field_collection() {
    check::<endpoint::GetExtraInputFieldCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_factor_groups_collection() {
    check::<endpoint::GetFactorGroupsCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_factors_collection() {
    check::<endpoint::GetFactorsCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_file_folder_collection() {
    check::<endpoint::GetFileFolderCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_file_collection() {
    check::<endpoint::GetFileCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_folder_collection() {
    check::<endpoint::GetFolderCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_invitations_collection() {
    check::<endpoint::GetInvitationsCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_invoice_line_collection() {
    check::<endpoint::GetInvoiceLineCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_factuur_collection() {
    check::<endpoint::GetFactuurCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_leave_mutations_collection() {
    check::<endpoint::GetLeaveMutationsCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_leave_request_collection() {
    check::<endpoint::GetLeaveRequestCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_leave_types_collection() {
    check::<endpoint::GetLeaveTypesCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_ledger_collection() {
    check::<endpoint::GetLedgerCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_payment_collection() {
    check::<endpoint::GetPaymentCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_project_crew_collection() {
    check::<endpoint::GetProjectCrewCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_project_equipment_collection() {
    check::<endpoint::GetProjectEquipmentCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_project_equipment_group_collection() {
    check::<endpoint::GetProjectEquipmentGroupCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_project_function_group_collection() {
    check::<endpoint::GetProjectFunctionGroupCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_project_function_collection() {
    check::<endpoint::GetProjectFunctionCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_project_request_equipment_collection() {
    check::<endpoint::GetProjectRequestEquipmentCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_project_request_collection() {
    check::<endpoint::GetProjectRequestCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_project_collection() {
    check::<endpoint::GetProjectCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_project_type_collection() {
    check::<endpoint::GetProjectTypeCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_project_vehicle_collection() {
    check::<endpoint::GetProjectVehicleCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_purchase_order_cost_collection() {
    check::<endpoint::GetPurchaseOrderCostCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_purchase_order_global_cost_collection() {
    check::<endpoint::GetPurchaseOrderGlobalCostCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_purchase_order_collection() {
    check::<endpoint::GetPurchaseOrderCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_quotation_collection() {
    check::<endpoint::GetQuotationCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_crew_rate_factor_collection() {
    check::<endpoint::GetCrewRateFactorCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_crew_rate_collection() {
    check::<endpoint::GetCrewRateCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_repair_collection() {
    check::<endpoint::GetRepairCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_serial_number_collection() {
    check::<endpoint::GetSerialNumberCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_status_collection() {
    check::<endpoint::GetStatusCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_stock_location_collection() {
    check::<endpoint::GetStockLocationCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_stock_movement_collection() {
    check::<endpoint::GetStockMovementCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_subproject_collection() {
    check::<endpoint::GetSubprojectCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_subrental_equipment_collection() {
    check::<endpoint::GetSubrentalEquipmentCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_subrental_equipment_group_collection() {
    check::<endpoint::GetSubrentalEquipmentGroupCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_subrental_collection() {
    check::<endpoint::GetSubrentalCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_subtask_collection() {
    check::<endpoint::GetSubtaskCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_supplier_collection() {
    check::<endpoint::GetSupplierCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_task_assignment_collection() {
    check::<endpoint::GetTaskAssignmentCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_task_collection() {
    check::<endpoint::GetTaskCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_task_status_collection() {
    check::<endpoint::GetTaskStatusCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_tax_class_collection() {
    check::<endpoint::GetTaxClassCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_time_registration_collection() {
    check::<endpoint::GetTimeRegistrationCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_time_registration_activity_collection() {
    check::<endpoint::GetTimeRegistrationActivityCollectionEndpoint>().await;
}

#[tokio::test]
#[ignore = "calls the real Rentman API; requires RENTMAN_API_TOKEN"]
async fn get_vehicle_collection() {
    check::<endpoint::GetVehicleCollectionEndpoint>().await;
}
